import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import NavBar from './components/NavBar/NavBar';
import { Suspense } from 'react';
import AuthProvider from './auth/Provider';

const inter = Inter({ subsets: ['latin'] });

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500'],
});

const komigo = localFont({
  src: '../public/fonts/Komigo3D-Regular.ttf',
  variable: '--font-komigo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <AuthProvider>
        <body className={komigo.variable}>
          <NavBar />
          {/* <Suspense fallback={<p>Loading...</p>}>
            <main className="p-5">{children}</main>
          </Suspense> */}
          <main className="p-5">{children}</main>
        </body>
      </AuthProvider>
    </html>
  );
}
